baseURL = 'https://www.chalatu.xyz/'
defaultContentLanguage = 'zh-cn'
defaultContentLanguageInSubdir = false
enableRobotsTXT = true
hasCJKLanguage = true
theme = 'PaperModLocal'
title = '查拉图的数字花园'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[languages]
  [languages.zh-cn]
    languageCode = 'zh-CN'
    languageName = '简体中文'
    title = '查拉图的数字花园'
    weight = 1

[params]
  description = '发布关于哲学与思考、一人公司的观点文章与深度长文。'
  defaultTheme = 'auto'
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowToc = true

  [params.assets]
    favicon = 'favicon-32x32.png'
    favicon16x16 = 'favicon-16x16.png'
    favicon32x32 = 'favicon-32x32.png'
    apple_touch_icon = 'apple-touch-icon.png'
    safari_pinned_tab = 'safari-pinned-tab.svg'
    theme_color = '#2e2e33'
    msapplication_TileColor = '#2e2e33'

[[menu.main]]
  name = '哲学与思考'
  url = '/posts/philosophy/'
  weight = 1

[[menu.main]]
  name = '一人公司'
  url = '/posts/solo-company/'
  weight = 2
